FC = gfortran

flags_gfortran = -std=f2008 -pedantic -Wall -Wno-maybe-uninitialized
flags_ifort = -O0 -stand f08 -warn all
flags_ifx = ${flags_ifort}

FFLAGS = ${flags_$(FC)}

# generated by makemake90 bin=bin mod=build obj=build src=src:

modules_gfortran = -Jbuild
modules_ifort = -module build
modules_ifx = ${modules_ifort}

override FFLAGS += ${modules_$(FC)}

needless += build/aiff.o build/aiff2riff.o build/bytes.o build/cgi.o build/constants.o build/extended.o build/fjs.o build/guitar.o build/harmonics.o build/id3.o build/inspect.o build/interpreter.o build/intervals.o build/io.o build/lcg.o build/mel.o build/mono.o build/paths.o build/rationals.o build/repeat.o build/riff.o build/riff2aiff.o build/samples.o build/search.o build/spectra.o build/stack.o build/stick.o build/stretch.o build/synthesis.o build/tab.o build/tag.o build/trim.o build/tz.o build/*.mod

programs = bin/tz bin/tz.cgi

.PHONY: all clean cleaner

all: $(programs)

clean:
	rm -f $(needless)

cleaner: clean
	rm -f $(programs)

$(programs):
	$(FC) $(FFLAGS) -o $@ $^ $(LDLIBS)

build/%.o: src/%.f90
	$(FC) $(FFLAGS) -c $< -o $@

bin/tz: build/aiff.o build/aiff2riff.o build/bytes.o build/constants.o build/extended.o build/fjs.o build/guitar.o build/harmonics.o build/id3.o build/inspect.o build/interpreter.o build/intervals.o build/io.o build/lcg.o build/mel.o build/mono.o build/paths.o build/rationals.o build/repeat.o build/riff.o build/riff2aiff.o build/samples.o build/search.o build/spectra.o build/stack.o build/stick.o build/stretch.o build/synthesis.o build/tab.o build/tag.o build/trim.o build/tz.o
bin/tz.cgi: build/bytes.o build/cgi.o build/constants.o build/extended.o build/fjs.o build/interpreter.o build/intervals.o build/io.o build/lcg.o build/rationals.o build/riff.o build/samples.o build/search.o build/synthesis.o build/tab.o

build/aiff.o: build/bytes.o build/constants.o build/extended.o
build/aiff2riff.o: build/aiff.o build/constants.o build/io.o build/riff.o
build/bytes.o: build/constants.o
build/cgi.o: build/constants.o build/interpreter.o build/io.o build/riff.o build/tab.o
build/extended.o: build/constants.o
build/fjs.o: build/constants.o
build/guitar.o: build/constants.o build/io.o build/tab.o
build/harmonics.o: build/constants.o build/io.o build/samples.o build/spectra.o
build/id3.o: build/constants.o build/io.o build/paths.o
build/inspect.o: build/aiff.o build/constants.o build/id3.o build/io.o build/paths.o build/riff.o
build/interpreter.o: build/constants.o build/fjs.o build/io.o build/lcg.o build/rationals.o build/riff.o build/samples.o build/search.o build/synthesis.o
build/intervals.o: build/constants.o
build/io.o: build/constants.o
build/lcg.o: build/constants.o
build/mel.o: build/constants.o build/interpreter.o build/io.o build/riff.o
build/mono.o: build/constants.o build/io.o build/riff.o
build/rationals.o: build/constants.o
build/repeat.o: build/constants.o build/io.o build/rationals.o build/riff.o
build/riff.o: build/bytes.o build/constants.o build/extended.o
build/riff2aiff.o: build/aiff.o build/constants.o build/io.o build/riff.o
build/samples.o: build/constants.o build/intervals.o build/lcg.o
build/search.o: build/constants.o
build/spectra.o: build/constants.o
build/stack.o: build/constants.o build/io.o build/riff.o
build/stick.o: build/constants.o build/io.o build/riff.o
build/stretch.o: build/constants.o build/io.o build/rationals.o build/riff.o
build/synthesis.o: build/constants.o build/lcg.o
build/tag.o: build/constants.o build/id3.o build/io.o build/paths.o build/riff.o
build/trim.o: build/constants.o build/io.o build/rationals.o build/riff.o
build/tz.o: build/aiff2riff.o build/guitar.o build/harmonics.o build/inspect.o build/io.o build/mel.o build/mono.o build/repeat.o build/riff2aiff.o build/stack.o build/stick.o build/stretch.o build/tag.o build/trim.o
