#!/usr/bin/env python

from os import listdir
from re import search, IGNORECASE as i

compiler = 'gfortran'
options = '-std=f2003 -Wall -pedantic' # -O3 -fcheck=all
executable = 'tonbandfetzen'

F90 = sorted(file for file in listdir('.') if '.f90' in file)

O = [f90.replace('.f90', '.o') for f90 in F90]

with open('makefile', 'w') as makefile:
    makefile.write('''# generated by makemake.py

COMPILER = {compiler}
OPTIONS = {options}
EXECUTABLE = {executable}

$(EXECUTABLE): {objects}
\t@echo linking $@
\t@$(COMPILER) -o $@ $^

%.o: %.f90
\t@echo compiling $*
\t@$(COMPILER) $(OPTIONS) -c $<
'''.format(objects=' '.join(O), **vars()))

    for f90, o in zip(F90, O):
        makefile.write('\n' + o + ':')

        with open(f90) as code:
            for line in code:
                use = search(r'^\s*use\s+(\w+)', line, i)
                if use:
                    makefile.write(' ' + use.group(1) + '.o')

    makefile.write('''

.PHONY: clean cleaner

clean:
\trm -f *.o *.mod

cleaner: clean
\trm -f $(EXECUTABLE)
''')
