.\" Man page for the command aiff2riff of the Tonbandfetzen tool box
.TH AIFF2RIFF 1 2020 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
aiff2riff \- convert .aif(f) into .wav(e) files
.SH SYNOPSIS
.BI aiff2riff
.IR infile
.IR outfile
.SH DESCRIPTION
.PP
Convert
.IR infile
in the Audio Interchange File Format (AIFF, developed by Apple) into
.IR outfile
in the Waveform Audio File Format (RIFF/WAVE, developed by IBM and Microsoft). Both store uncompressed audio data in a chunk-based container format. The main difference is that AIFF and WAVE employ the big-endian and little-endian byte order, respectively.
