.\" Man page for the command guitar of the Tonbandfetzen tool box
.TH GUITAR 1 2010\(en2023 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
guitar \- read guitar tablature
.SH SYNOPSIS
.BI guitar
.RI [ infile
.RI [ outfile ]]
.SH DESCRIPTION
.PP
Preprocess input for the program
.BR mel
to allow for guitar tablatures.
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
.SH SYNTAX
The syntax of
.IR infile
is as described in
.BR mel (1),
with the following exception:
Text between two vertical bars
.RB ( | )
that contains at least one hyphen-minus
.RB ( - )
or tilde
.RB ( \(ti ),
represents one bar/measure.
Here, the commands
.RI \fB|\fR n ,
.RI \fB\-\fR n ,
.RI \fBX\fR w [...],
and
.RI \fB\(ti\fR w [ n ]
cannot be applied as usual and the
.BR U
of the
.BI U n
command can be omitted.
The bar duration, defined beforehand via the
.BI | n
command, is evenly distributed among the enclosed characters.
The hyphen-minus
.RB ( - )
and
.BR X
represent a string at rest and a muted string (a pause); the tilde
.RB ( \(ti )
represents a vibrating string (sound is played), just like all other characters, beyond their usual meanings.
Lines with tablature that are not separated by an empty line start at the same point in time.
This is realized via the
.BR M0
mark, which shall thus not be used.
