.\" Man page for the command harmonics of the Tonbandfetzen tool box
.TH HARMONICS 1 2020 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
harmonics \- show spectra of wave samples
.SH SYNOPSIS
.BI harmonics
.IR label
.SH DESCRIPTION
.PP
Show Fourier analysis of predefined wave sample with given
.IR label .
