.\" Man page for the command inspect of the Tonbandfetzen tool box
.TH INSPECT 1 2010\(en2022 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
inspect \- show information on audio file
.SH SYNOPSIS
.BI inspect
.RI [ file ]
.SH DESCRIPTION
.PP
Show basic information about
.IR file ,
which defaults to
.BR /dev/stdin .
Only WAVE and AIFF files are supported.
The format is inferred from the extension
.RB ( .wav / .wave / none
or
.BR .aif / .aiff ).
