.\" Man page for the command mel of the Tonbandfetzen tool box
.TH MEL 1 2020 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
mel \- generate sound fragments from plain text
.SH SYNOPSIS
.BI mel
.RI [[[ wavefile " ...]"
.IR infile ]
.IR outfile ]
.SH DESCRIPTION
.PP
Interpret ASCII input in
.IR infile
as audio and save it to
.IR outfile
in the WAVE format, optionally using samples provided in
.IR wavefile s.
The syntax for
.IR infile
is given below.
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
.SH SYNTAX
.IR infile
shall contain words
.IR w
(sequences of lowercase letters
.BR a " to " z " and hashes " # ),
numbers
.IR n
(sequences of digits
.BR 0 " to " 9 ,
decimal points
.BR . ,
and a dividing colon
.BR : ),
and commands (other single ASCII characters).
Commands are followed by words and/or numbers as arguments, as listed below.
The input is processed linearly, whereby unexpected characters, including whitespace, act as separators and are otherwise ignored.
.TP
.BI ~ w " " n
Choose wave sample of shape
.IR w
and duration
.IR n
in seconds.
This is the building block for sound at arbitrary frequency and amplitude.
Predefined values for
.IR w
are listed below.
The corresponding spectra are shown by the command
.BI harmonics
.IR w .
If
.IR w
reads
.BR # ,
the first channel of the
.IR n th
.IR wavefile
given on the command line is loaded instead.
The default is a
.BR circular
wave that lasts
.BR 1
second.
.RS
.TP
.BR harmonic
sin(x) for x in (0, 2\[*p]]
.TP
.BR power
sin\[S3](x) for x in (0, 2\[*p]]
.TP
.BR major
sin\[u2075](x) for x in (0, 2\[*p]]
.TP
.BR constant
sgn(sin(x)) for x in (0, 2\[*p]]
.TP
.BR linear
2/\[*p] arcsin(sin(x)) for x in (0, 2\[*p]]
.TP
.BR quadratic
sgn(x) (2|x| - x\[S2]) for x in (-2, 2]
.TP
.BR circular
sgn(x) sqrt(2|x| - x\[S2]) for x in (-2, 2]
.TP
.BR cubic
3/2 sqrt(3) (x\[S3] - x) for x in (-1, 1]
.TP
.BR random
white noise
.RE
.TP
.BI S w " " n
Choose attack envelope of shape
.IR w
and duration
.IR n
in seconds.
Predefined values for
.IR w
are listed below.
The default is a
.BR circular
envelope that lasts
.BR 0.1
seconds.
.RS
.TP
.BR harmonic
sin(x) for x in (0, \[*p]/2)
.TP
.BR smooth
sin\[S2](x) for x in (0, \[*p]/2)
.TP
.BR power
sin\[S3](x) for x in (0, \[*p]/2)
.TP
.BR major
sin\[u2075](x) for x in (0, \[*p]/2)
.TP
.BR linear
x for x in (0, 1)
.TP
.BR quadratic
1 - x\[S2] for x in (-1, 0)
.TP
.BR circular
sqrt(1 - x\[S2]) for x in (-1, 0)
.TP
.BR cubic
3x\[S2] - 2x\[S2] for x in (0, 1)
.RE
.TP
.BI Z w " " n
Choose release envelope.
Arguments as above.
.TP
.BI N w " " n
Choose attack and release envelope at once.
Arguments as above.
.TP
.BI *
Start/end a comment.
.TP
.BI $ n
Set a sample rate of
.IR n
samples per second.
The default is
.BR 44100
samples per second.
This setting holds globally and is ignored after first note played.
.TP
.BI O n
Set number of channels to
.IR n .
Allowed values are
.BR 1
(mono) and
.BR 2
(stereo).
The default is
.BR 2 .
This setting holds globally and is ignored after first note played.
.TP
.BI | n
Set duration of a beat to
.IR n
seconds.
The default is
.BR 0.5
seconds.
.TP
.BI @ n
Set concert pitch
.BR A4
to
.IR n
Hz.
The default is
.BR 440
Hz.
.TP
.BI T w
Choose tuning from the below options.
.RS
.TP
.BR equal
Equal temperament.
.TP
.BR fifth
Pythagorean tuning. All notes are reached combining fifths and octaves.
.TP
.BR just
Just intonation. All notes are reached combining thirds, -1 to 2 fifths from keynote, and octaves.
.RE
.TP
.BI H n
Divide one octave into
.IR n
halftones/steps of equal frequency ratio.
The default is
.BR 12
halftones (twelve-tone equal temperament).
.TP
.BI = n
Set reference frequency to
.IR n
Hz.
The default is the concert pitch
.BR A4 .
.TP
.BI & n
Set reference amplitude sqrt(L\[S2] + R\[S2]) to
.IR n
arb. units.
The default is
.BR 1
arb. unit.
.TP
.BI % n
Set reference amplitude ratio R:L between right and left channel to
.IR n .
The default is
.BR 1 .
.TP
.RI "\fBC D E F G A B\fR[" w ][ n ]
Set reference frequency via note name.
.IR w
marks accidentals and can be
.BR # ,
.BR x ,
.BR b ,
.BR bb ,
and so on.
.IR n
is the octave number.
If omitted, set the keynote.
.BI A4
is the concert pitch.
.TP
.RI \fB'\fR[ n ]
Play sound for a duration of
.IR n
beats.
.IR n
defaults to
.BR 1 .
.TP
.RI \fB\(dq\fR[ n ]
Pause for a duration of
.IR n
beats.
.IR n
defaults to
.BR 1 .
.TP
.RI \fB`\fR[ n ]
Rewind by
.IR n
beats.
.IR n
defaults to
.BR 1 .
(Negative pause.)
.TP
.BI "- +" n
Set frequency to
.IR n
halftones below/above the reference.
.TP
.BI "\e /" n
Continuously lower/raise frequency by
.IR n
halftones during the next play period
.RB ( ' ).
.TP
.BI "_ ^" n
Continuously lower/raise frequency by
.IR n
halftones per beat from now on.
.TP
.BI "? !" n
Set amplitude to
.IR n
dB below/above the reference.
.TP
.BI "< >" n
Continuously lower/raise amplitude by
.IR n
dB during the next play period
.RB ( ' ).
.TP
.BI ", ;" n
Continuously lower/raise amplitude by
.IR n
dB per beat from now on.
.TP
.BI "[ ]" n
Set amplitude ratio to
.IR n
dB below/above the reference.
.TP
.BI "( )" n
Continuously lower/raise amplitude ratio by
.IR n
dB during the next play period
.RB ( ' ).
.TP
.BI "{ }" n
Continuously lower/raise amplitude ratio by
.IR n
dB per beat from now on.
.TP
.BI M n
Set
.IR n th
time mark.
.IR n
must be an integer between
.BR 0 " and " 99 .
.TP
.BI W n
Wind back to
.IR n th
time mark.
.TP
.BI P n " " n'
Paste copy of sound between
.IR n th
and
.IR n' th
time mark.
.TP
.BI R n " " n' " " n\(dq
Repeat copy of sound between
.IR n th
and
.IR n' th
time mark
.IR n\(dq
times.
.TP
.BI I n
Set
.IR n th
text mark.
.IR n
must be an integer between
.BR 0 " and " 99 .
.TP
.BI J n " " n'
Jump back to
.IR n th
text mark.
This works
.IR n'
times in a row.
.TP
.BI X n
Randomly detune frequency, including concert pitch
.BR A4 ,
by up to
.IR n
halftones.
In combination with text and time marks, this is useful to generate non-white noise.
.TP
.BI L n " " n' " " m " " m'
Apply flanger to sound between
.IR n th
and
.IR n' th
time mark.
The sample is periodically delayed (and advanced) with an amplitude of
.IR m
seconds and a frequency of
.IR m'
per sample length, using the current wave sample, and superimposed with itself.
.TP
.BI V n " " n'
Set vibrato with amplitude of
.IR n
Hz and frequency of
.IR n'
Hz.
