.\" Man page for the command repeat of the Tonbandfetzen tool box
.TH REPEAT 1 2010\(en2022 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
repeat \- loop audio data
.SH SYNOPSIS
.BI repeat
.RI [ count
.RI [ infile
.RI [ outfile [\fB/\fR]]]]
.SH DESCRIPTION
.PP
Repeat the audio data in
.IR infile
.IR count
times and store the result in
.IR outfile .
Fractional
.IR count s
like
.BR 0.5 ,
.BR 1/3 ,
or
.BR 1:4
are permitted.
Negative fractional
.IR count s
put the incomplete part in the beginning.
All files must be in the WAVE format.
.IR count
defaults to
.BR 2 .
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
If
.IR outfile
is followed by a slash
.RB ( / ) ,
application-specific metadata is omitted.
