.\" Man page for the command riff2aiff of the Tonbandfetzen tool box
.TH RIFF2AIFF 1 2010\(en2022 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
riff2aiff \- convert .wav(e) into .aif(f) files
.SH SYNOPSIS
.BI riff2aiff
.RI [[ infile ]
.IR outfile [\fB/\fR]]
.SH DESCRIPTION
.PP
Convert
.IR infile
in the Waveform Audio File Format (RIFF/WAVE, developed by IBM and Microsoft) into
.IR outfile
in the Audio Interchange File Format (AIFF, developed by Apple).
Both store uncompressed audio data in a chunk-based container format.
The main difference is that WAVE and AIFF employ the little-endian and big-endian byte order, respectively.
.IR infile
and
.IR outfile
default to
.BR /dev/stdin
and
.BR /dev/stdout ,
respectively.
The dash
.RB ( - )
is a shorthand for the default value.
If
.IR outfile
is followed by a slash
.RB ( / ) ,
application-specific metadata is omitted.
