.\" Man page for the command stick of the Tonbandfetzen tool box
.TH STICK 1 2010\(en2022 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
stick \- concatenate audio data
.SH SYNOPSIS
.BI stick
.RI [[ infile " ...]"
.IR outfile [\fB/\fR]]
.SH DESCRIPTION
.PP
Concatenate the audio data from the given
.IR infile s
and store the result in
.IR outfile .
All files must be in the WAVE format.
The
.IR infile s
and
.IR outfile
default to
.BR /dev/stdin
and
.BR /dev/stdout ,
respectively.
The dash
.RB ( - )
is a shorthand for the default value.
If
.IR outfile
is followed by a slash
.RB ( / ) ,
application-specific metadata is omitted.
