.\" Man page for the command stick of the Tonbandfetzen tool box
.TH STICK 1 2020 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
stick \- concatenate audio data
.SH SYNOPSIS
.BI stick
.RI [ infile " ...]"
.IR outfile
.SH DESCRIPTION
.PP
Concatenate the audio data from the given
.IR infile s
and store the result in
.IR outfile .
All files must be in the WAVE format.
