.\" Man page for the command tag of the Tonbandfetzen tool box
.TH TAG 1 2010\(en2024 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
tag \- add ID3v2 metadata to .wav(e) files
.SH SYNOPSIS
.BI tag
.RI [ infile
.RI [ datafile
.RI [ outfile ]]]
.SH DESCRIPTION
.PP
Add metadata in the ID3v2 format to the content of
.IR infile
and store the result in
.IR outfile .
The IDv3 metadata is provided via a UTF-8-encoded
.IR datafile ,
where each lines consists of an ID3 frame ID followed by a single space and the actual information, for example:
.PP
.RS
.nf
TIT2 Explosion
TALB Kapitulation
TPE1 Tocotronic
TYER 2007
TRCK 12/12
APIC Portrait_of_Douglass_Morgan_Hall.png
.fi
.RE
.PP
Currently, only text-information frames, whose frame IDs start with "T", and an attached picture (APIC) are supported.
Existing IDv3 metadata is overwritten.
Tonbandfetzen metadata, namely the amplitude stored in the application-specific
.BR APPL
chunk, is cleared.
.IR infile
defaults to
.BR /dev/stdin .
If nonexistent or empty, all metadata is cleared.
.IR datafile
defaults to the filename stem of
.IR infile
with the extension
.BR .id3 .
.IR outfile
defaults to
.IR infile
where the possible substring
.BR stdin
is replaced by
.BR stdout .
The dash
.RB ( - )
is a shorthand for the default value.
