.\" Man page for the command guitar of the Tonbandfetzen tool box
.TH TZ-GUITAR 1 2010\(en2026 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
tz guitar \- read guitar tablature
.SH SYNOPSIS
.B tz guitar
.RI [ infile
.RI [ outfile ]]
.SH DESCRIPTION
.PP
Preprocess input for the program
.B tz mel
to allow for guitar tablatures.
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
.SH SYNTAX
The syntax of
.IR infile
is as described in
.BR tz-mel (1),
with the following exception:
If a line contains at least two vertical bars
.RB ( | ),
they act as separators between regions.
If a region contains at least one of the commands
.BR | ,
.BR - ,
.BR _ ,
.BR N ,
.BR \(ti ,
.BR \(ha ,
.BR S ,
.BR Z ,
.BR T ,
and
.BR X ,
it represents one bar/measure.
Here, these commands act differently and the
.BR U
of an ensuing
.BI U n
can be omitted.
The bar duration, defined beforehand via the
.BI | n
command, is evenly distributed among the enclosed characters.
The hyphen-minus
.RB ( - ),
the underscore
.RB ( _ ),
and
.BR N
represent a string at rest (a pause); the tilde
.RB ( \(ti ),
the circumflex
.RB ( \(ha ),
.BR S ,
.BR Z ,
.BR T ,
and
.BR X
represent a vibrating string (sound is played), just like all other characters, beyond their usual meanings.
Here,
.BR \(ha
(hammer-on or pull-off),
.BR S / Z
(slide down/up), and
.BR T
(tap) imply a legato transition to the ensuing note, while
.BR X
(rhythm) ends the previous note and plucks the string (or beats the drum) again.
.BR N
(no sound) could denote a muted string.
Lines with tablature that are not separated by an empty line start at the same point in time.
This is realized via the
.BR M0
mark, which shall thus not be used.
