.\" Man page for the command harmonics of the Tonbandfetzen tool box
.TH TZ-HARMONICS 1 2010\(en2025 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
tz harmonics \- show spectra of wave samples
.SH SYNOPSIS
.B tz harmonics
.RI [ label ]
.SH DESCRIPTION
.PP
Show Fourier analysis of predefined wave sample with given
.IR label ,
which defaults to
.BR circular .
