.\" Man page for the command stick of the Tonbandfetzen tool box
.TH TZ-STICK 1 2010\(en2025 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
tz stick \- concatenate audio data
.SH SYNOPSIS
.B tz stick
.RI [[ infile " ...]"
.IR outfile ]
.SH DESCRIPTION
.PP
Concatenate the audio data from the given
.IR infile s
and store the result in
.IR outfile .
All files must be in the WAVE format.
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
