.\" Man page for the command stack of the Tonbandfetzen tool box
.TH TZ-STACK 1 2010\(en2025 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
tz stack \- superimpose audio data
.SH SYNOPSIS
.B tz stack
.RI [[ infile " ...]"
.IR outfile ]
.SH DESCRIPTION
.PP
Superimpose the audio data from the given
.IR infile s
and store the result in
.IR outfile .
Shorter data (with respect to both the number of channels and sample points) is periodically repeated.
All files must be in the WAVE format.
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
