.\" Man page for the command stretch of the Tonbandfetzen tool box
.TH TZ-STRETCH 1 2010\(en2025 "Jan Berges" "Tonbandfetzen Manual"
.SH NAME
tz stretch \- rescale audio data
.SH SYNOPSIS
.B tz stretch
.RI [ factor
.RI [ infile
.RI [ outfile ]]]
.SH DESCRIPTION
.PP
Speed up the audio data in
.IR infile
by the given
.IR factor
and store the result in
.IR outfile .
Fractional
.IR factor s
like
.BR 0.5 ,
.BR 1/3 ,
or
.BR 1:4
are permitted.
For negative
.IR factor s,
the audio data is reversed.
All files must be in the WAVE format.
.IR factor
defaults to
.BR -1 .
Filenames default to
.BR /dev/stdin
or
.BR /dev/stdout .
The dash
.RB ( - )
is a shorthand for the default value.
